### ISSUE TITLE
[#0102] Datalogger - Cadastrar medidas da estação (Mock)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-iot#3]
<h2>Sobre a tarefa</h2>

- Criar mock para enviar medidas da estação;
- Enviar medidas com unixTime;
- Enviar dados a cada 1h

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
<h2>Cadastro de medidas (Mock)</h2>

- Adicionando epoch/unix time 
![image](https://user-images.githubusercontent.com/80930525/199612619-7aecdbd2-b77e-406e-992b-25c1bde6f787.png)
![image](https://user-images.githubusercontent.com/80930525/199613076-a2ba7876-8bf3-444d-b781-ed7264132e03.png)

- Gerando números variáveis  
![image](https://user-images.githubusercontent.com/80930525/199613259-dacd331d-30ab-47c1-a8f9-b09300ec2147.png)

- Formato do Json 
"{\"stationId\":\"C14H\", \"measurements\":{\"temp\":\"" + String(temp) + "\", \"pluv\": \"" + String(pluv) +"\", \"windSpeed\": \"" + String(windSpeed) + "\", \"umi\": \"" + String(umi) + "\" },  \"moment\":\"" + String(epochTime) + "\"}"

-Dados cadastrados
3:Temperatura, 4:Chuva,9:vento, 10:umidade
![image](https://user-images.githubusercontent.com/80930525/199614131-46b421c9-06db-4ea1-b5ab-eddb91db8290.png)
