### ISSUE TITLE
[#0104]  Datalogger - Bill of Materials (BOM)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-iot#4]
## Sobre a Tarefa

Levantar Bill of Materials confome solicitado pelo cliente no dia 25/10/2022

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by ThHenrique** [comment]
## Documentação

- Conforme solicitado pelo cliente, abaixo está nosso BOM

![Image](https://user-images.githubusercontent.com/58437896/199578746-e03bb117-ce8f-4c34-8506-2b45e67a2862.png)
